### ISSUE TITLE
1.0.36の性能改造にて、速度欄が修正できない

### ISSUE THREAD

**Issue by AYLYC** [khttemp/dend-mod-gui#3]
**環境**

OS: Windows11 64bit
dend-mod-gui 1.0.36

**現象**

全てのステージの性能改造において、速度欄の数値を変更しても修正ボタンを押しても反映されません。

**再現手順**

main.exeバージョン 1.0.36 を起動します。
改造プログラム性能改造を選択します
任意のステージを選択します。
速度欄の修正を押しても反応しないことを確認します

この問題は、main.exe 1.0.35 では発生していませんでした。
以上、ご確認よろしくお願いいたします。

**Comment by khttemp** [comment]
修正完了
